before_script:
  - export PYTHONPATH=$PWD
  - virtualenv -p python3.7 venv
  - source venv/bin/activate
  - python tests/manage_gitlab-ci.py setup

test:
  tags:
  - development
  script:
  - python tests/manage_gitlab-ci.py run
