# Generated by Django 2.2.4 on 2019-09-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_globalpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'permissions': [('add_book_style', 'Add book style'), ('delete_book_style', 'Delete book style'), ('edit_book_style', 'Edit book style'), ('change_default_model_for_book_style', 'Change default model for book style'), ('tasks_list', 'List tasks'), ('tasks_cancel', 'Cancel a running task')]},
        ),
    ]
