# Generated by Django 5.2 on 2026-07-17 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_populate_lyrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIndex',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('meta_mtime', models.FloatField(default=0.0)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('notation_style', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookDocumentsIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.JSONField(null=True)),
                ('file_mtime', models.FloatField(default=0.0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_index', to='database.bookindex')),
            ],
        ),
        migrations.CreateModel(
            name='PageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pcgts_mtime', models.FloatField(default=0.0)),
                ('progress_mtime', models.FloatField(default=0.0)),
                ('has_symbols', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('progress_locks', models.JSONField(default=dict)),
                ('counts', models.JSONField(blank=True, null=True)),
                ('counts_mtime', models.FloatField(default=0.0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='database.bookindex')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('book', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PageEditLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='database.pageindex')),
            ],
        ),
    ]
