# Generated by Django 5.2 on 2026-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_bookindex_bookdocumentsindex_pageindex_pageeditlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdocumentsindex',
            name='file_mtime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookindex',
            name='meta_mtime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='counts_mtime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='pcgts_mtime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageindex',
            name='progress_mtime',
            field=models.BigIntegerField(default=0),
        ),
    ]
