# Generated by Django 5.2 on 2026-08-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_globalpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'permissions': [('add_book_style', 'Add book style'), ('delete_book_style', 'Delete book style'), ('edit_book_style', 'Edit book style'), ('change_default_model_for_book_style', 'Change default model for book style'), ('tasks_list', 'List tasks'), ('tasks_cancel', 'Cancel a running task'), ('set_training_epochs', 'Raise the number of training epochs above the default'), ('view_system_resources', 'View the server resources'), ('manage_models', 'List and delete trained models'), ('manage_task_workers', 'Repair the task scheduler and release worker slots')]},
        ),
    ]
