# Generated by Django 5.2 on 2026-09-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_globalpermissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'permissions': [('add_book_style', 'Add book style'), ('delete_book_style', 'Delete book style'), ('edit_book_style', 'Edit book style'), ('add_symbol_class', 'Add symbol class'), ('delete_symbol_class', 'Delete symbol class'), ('edit_symbol_class', 'Edit symbol class'), ('change_default_model_for_book_style', 'Change default model for book style'), ('tasks_list', 'List tasks'), ('tasks_cancel', 'Cancel a running task'), ('set_training_epochs', 'Raise the number of training epochs above the default'), ('view_system_resources', 'View the server resources'), ('manage_models', 'List and delete trained models'), ('manage_task_workers', 'Repair the task scheduler and release worker slots')]},
        ),
        migrations.CreateModel(
            name='SymbolClass',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_symbol_type', models.CharField(max_length=16)),
                ('base_sub_type', models.CharField(max_length=32)),
                ('clef_offset', models.IntegerField(blank=True, null=True)),
                ('glyph_preset', models.CharField(blank=True, default='', max_length=32)),
                ('svg_path', models.TextField(blank=True, default='')),
                ('svg_path_stroke', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('digit_shortcut', models.IntegerField(blank=True, null=True)),
                ('hidden_by_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_classes', to='database.bookstyle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
